name: generate asccii artwork

on: 
    workflow_dispatch:
#test
jobs: 
    First_job:
     
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: install cowsay program
              run: sudo apt-get install cowsay -y

            - name: execute cowsay CMD
              run: cowsay -f ${{ vars.ANIMAL }} "run for cover, I am a DRAGON...RAWR" >> dragon.txt

            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: My artifact
                path: dragon.txt

                
    Second_job:
        needs: First_job
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: download artifact
              uses: actions/download-artifact@v4
              with:
                name: My artifact

            - name: test file exists
              run: grep -i "dragon" dragon.txt

            - name: read file
              run: cat dragon.txt

            - name: checkout repo files
              run: ls -ltra